---

language: python

services:
  - docker

before_install:
  - pip install -r requirements.txt
  - pip install yamllint
  - sudo apt-get -y install sshpass
  - chmod 600 tests/files/id_ed25519

install:
  - make docker

script:
  - make lint
  - make test
  - make test-idempotence

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
